window.streams = {
    timeRefresh: 10000,
    stations: [
        {
            name: "FE 4:18",
            hash: "Radio OnLine",
            description: "AL AIRE 24/7",
            logo: "assets/jailson_logo.png",
            album: "assets/jailson_cover.png",
            cover: "assets/jailson_cover.png",
            api: "",
            //api: "api.php?url=https://stream.zeno.fm/yu61me5evq6uv",
            stream_url: "https://stream.zeno.fm/yu61me5evq6uv",
            tv_url: "",
            server: "",
            social: {
                whatsapp: "https://whatsapp.com/channel/0029VaQ9EQL9xVJXn4FNqw0N",
                 telegram: "https://t.me/radiofe418",
                facebook: "https://www.facebook.com/profile.php?id=61557265294587&mibextid=ZbWKwL",
                instagram: "https://www.instagram.com/radiofe418online?igsh=emxoNjhpM215ZGFo",
            },
            apps: {
                android: "",
                ios: "",
            },
        },
        {
            name: "",
            hash: "",
            description: "",
            logo: "",
            album: "",
            cover: "",
            api: "",
            //api: "",
            api: "",
            stream_url: "",
            tv_url: "",
            server: "",
            social: {
                facebook: "",
                twitter: "",
                instagram: "",
            },
            apps: {
                android: "#",
                ios: "#",
            },
        },
        {
            name: "",
            hash: "",
            description: "",
            logo: "",
            album: "",
            cover: "",
            //api: "",
            api: "",
            stream_url: "",
            //tv_url: "",
            server: "",
            social: {
                facebook: "",
                whatsapp: "",
                //twitter: "",
                //tiktok: "",
                //youtube: "",
                instagram: "",
            },
            apps: {
                android: "",
                ios: "",
            },
        },
    ],
};